List<String> courseList = [
  'Engineering',
  'Islamic education',
  'BIT',
  'Laws',
  'Mathemathics',
  'Pendidikan islam',
  'BCS',
  'Human Resources',
  'Irkhs',
  'Psychology',
  'KENMS',
  'Accounting ',
  'ENM',
  'Marine science',
  'KOE',
  'Banking Studies',
  'Business Administration',
  'Law',
  'KIRKHS',
  'Usuluddin ',
  'TAASL',
  'Engine',
  'ALA',
  'Biomedical science',
  'koe',
  'Kirkhs',
  'BENL',
  'Benl',
  'IT',
  'CTS',
  'engin',
  'Econs',
  'MHSC',
  'Malcom',
  'Kop',
  'Human Sciences ',
  'Biotechnology',
  'Communication ',
  'Diploma Nursing',
  'Pendidikan Islam ',
  'Radiography',
  'psychology',
  'Fiqh fatwa ',
  'DIPLOMA TESL',
  'Koe',
  'Fiqh',
  'Islamic Education',
  'Nursing ',
  'Pendidikan Islam',
];
